const neighborhoods_seed = [
"Fábrica",
"Mariano Procópio",
"Morro da Glória",
"Santa Catarina",
"Vale do Ipê",
"Jardim Glória",
"Santa Helena",
"Paineiras",
"Dom Bosco",
"São Mateus",
"Santa Cecília",
"Mundo Novo",
"Alto dos Passos",
"Boa Vista",
"Bom Pastor",
"Vila Ozanan",
"Poço Rico",
"Granbery",
"Centro",
"Botanágua",
"São Bernardo",
"Cesário Alvim",
"Vitorino Braga",
"São Benedito",
"Grajaú",
"Linhares",
"Santa Rita",
"N. S. Aparecida",
"Manoel Honório",
"Bonfim",
"Bairú",
"Progresso",
"Barreira do Triunfo",
"Represa",
"Benfica",
"Santa Cruz",
"Nova Era",
"Barbosa Lage",
"Remonta",
"Jóquei Clube",
"Jardim Natal",
"Industrial",
"Francisco Bernardino",
"Carlos Chagas",
"Cerâmica",
"São Dimas",
"Esplanada",
"Monte Castelo",
"Borboleta",
"Morro do Imperador",
"Martelos",
"São Pedro",
"Cruzeiro Santo Antônio",
"Nova Califórnia",
"Novo Horizonte",
"Aeroporto",
"Vila Ideal",
"Vila Olavo Costa",
"Furtado de Menezes",
"Floresta",
"Retiro",
"Santo Antônio",
"Lourdes",
"Costa Carvalho",
"Salvaterra",
"Sagrado Coração",
"São Geraldo",
"Santa Efigênia",
"Ipiranga",
"Teixeiras",
"Santa luzia",
"Bomba de Fogo",
"Graminha",
"Cascatinha",
]

module.exports = {neighborhoods_seed }
